import test from 'node:test';import assert from 'node:assert/strict';
import {AIProvider,generateAI} from '../src/ai.js';import {generateGuided} from '../src/engine.js';import {examples} from '../src/curriculum.js';import {stages} from '../src/schema.js';
const input={grade:5,subject:'Mathematics',competencyId:examples[1].id,competency:examples[1].competency,mode:'ai'};
const reply=output=>({ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify(output)}}],usage:{prompt_tokens:10,completion_tokens:20}})});
async function fixture(sessions=1){const p=await generateGuided({...input,mode:'guided',sessions});const parts={unpack:p.unpacking,context:p.analysis,outcomes:{sessions:p.sessions.map(({id,title,keyConcept,objectives})=>({id,title,keyConcept,objectives}))},review:p.review};for(const key of ['assessment','experiences','differentiation','ways'])parts[key]={sessions:p.sessions.map(s=>({id:s.id,[key]:s[key]}))};for(const s of p.sessions)parts[`session_${s.id}`]=Object.fromEntries(['id','assessment','experiences','differentiation','ways'].map(k=>[k,s[k]]));return parts;}
test('Gemini profile uses explicit reasoning and preserves strict local validation',async()=>{const f=await fixture();let request;const provider=new AIProvider({key:'fixture',base:'https://generativelanguage.googleapis.com/v1beta/openai',designModel:'gemini-3.8-flash',fetchImpl:async(_,o)=>{request=JSON.parse(o.body);return reply(f.outcomes);}});await provider.generateStructured({stage:'outcomes',schema:stages.outcomes,context:{classroom:{sessions:1}},instruction:'fixture'});assert.equal(request.reasoning_effort,'medium');assert.ok(request.max_completion_tokens>=3500);assert.equal(request.response_format.json_schema.strict,true);});
test('response-body deadline recovers a complete request through smaller sections',async()=>{const f=await fixture();const calls=[];const events=[];const provider=new AIProvider({key:'fixture',requestTimeoutMs:10,sleep:async()=>{},fetchImpl:async(_,o)=>{const {stage}=JSON.parse(JSON.parse(o.body).messages[1].content);calls.push(stage);if(stage==='ilawcraft')return {ok:true,json:async()=>new Promise(()=>{})};return reply(f[stage]);}});provider.onDiagnostic=async e=>events.push(e);const p=await generateAI(input,{provider});assert.equal(p.metadata.aiWorkflow,'staged-recovery');assert.equal(calls.filter(s=>s==='ilawcraft').length,3);assert.ok(calls.includes('experiences'));assert.equal(events.filter(e=>e.code==='timeout').length,3);assert.equal(p.quality.counts.error,0);});
test('network outage does not fan out into additional generation stages',async()=>{let calls=0;const provider=new AIProvider({key:'fixture',sleep:async()=>{},fetchImpl:async()=>{calls++;throw Error('private upstream details');}});await assert.rejects(()=>generateAI(input,{provider}),e=>e.code==='network'&&!e.message.includes('private'));assert.equal(calls,3);});
test('five sessions use bounded complete session calls and resume retained sessions',async()=>{const f=await fixture(5);const calls=[];const retained={};let fail=true;const provider=new AIProvider({key:'fixture',fetchImpl:async(_,o)=>{const {stage,context}=JSON.parse(JSON.parse(o.body).messages[1].content);calls.push(stage);if(stage.startsWith('session_'))assert.equal(context.classroom.sessions,1);if(stage==='session_s3'&&fail)return {ok:false,status:401,json:async()=>({error:{}})};return reply(f[stage]);}});const save=async(k,v)=>retained[k]=v;await assert.rejects(()=>generateAI({...input,sessions:5},{provider,checkpoint:{save}}),/key/);assert.ok(retained.session_s1&&retained.session_s2);assert.ok(!retained.session_s3);fail=false;const resumed=await generateAI({...input,sessions:5},{provider,checkpoint:{parts:retained,save}});assert.equal(resumed.sessions.length,5);assert.equal(resumed.metadata.aiWorkflow,'session-adaptive');assert.equal(calls.filter(s=>s==='session_s1').length,1);assert.equal(calls.filter(s=>s==='outcomes').length,1);assert.equal(calls.filter(s=>s==='session_s3').length,2);assert.equal(calls.length,10);assert.equal(resumed.quality.counts.error,0);});
test('failed automatic critique preserves complete AI draft with explicit pending review',async()=>{const f=await fixture();const provider=new AIProvider({key:'fixture',sleep:async()=>{},fetchImpl:async(_,o)=>{const {stage}=JSON.parse(JSON.parse(o.body).messages[1].content);if(stage==='review')return {ok:false,status:503,json:async()=>({error:{}})};return reply(f[stage]);}});const p=await generateAI({...input,aiWorkflow:'staged'},{provider});assert.equal(p.metadata.mode,'ai');assert.equal(p.metadata.status,'draft');assert.equal(p.metadata.automaticReview,'pending');assert.ok(p.quality.checks.some(c=>c.code==='automatic-review-pending'));assert.match(p.review.teacherReview,/did not finish/);assert.equal(p.quality.counts.error,0);});
test('bad assessment invalidates dependent content while retaining valid objectives',async()=>{const f=await fixture();const bad=structuredClone(f);bad.assessment.sessions[0].assessment[0].objectiveIds=['unknown'];const calls=[];const provider=new AIProvider({key:'fixture',fetchImpl:async(_,o)=>{const {stage}=JSON.parse(JSON.parse(o.body).messages[1].content);calls.push(stage);return reply(stage==='ilawcraft'?bad:f[stage]);}});const p=await generateAI(input,{provider});assert.deepEqual(calls,['ilawcraft','assessment','experiences','differentiation','ways','review']);assert.deepEqual(p.sessions[0].objectives,f.outcomes.sessions[0].objectives);assert.equal(p.quality.counts.error,0);});
test('cancellation during response-body read does not start recovery',async()=>{const controller=new AbortController();let calls=0;const provider=new AIProvider({key:'fixture',requestTimeoutMs:20,sleep:async()=>{},fetchImpl:async(_,o)=>{calls++;controller.abort();return {ok:true,json:async()=>{throw o.signal.reason;}};}});provider.signal=controller.signal;await assert.rejects(()=>generateAI(input,{provider}));assert.equal(calls,1);});

test('unsupported claims are quarantined and repaired without changing curriculum provenance',async()=>{const f=await fixture();const bad=structuredClone(f);bad.assessment.sessions[0].assessment[0].answerKey='This lesson is DepEd approved.';const retained={};const provider=new AIProvider({key:'fixture',fetchImpl:async(_,o)=>{const {stage}=JSON.parse(JSON.parse(o.body).messages[1].content);return reply(stage==='ilawcraft'?bad:f[stage]);}});const p=await generateAI(input,{provider,checkpoint:{save:async(k,v)=>retained[k]=v}});assert.ok(!JSON.stringify(retained).includes('DepEd approved'));assert.ok(!JSON.stringify(p.sessions).includes('DepEd approved'));assert.equal(p.source.competency,input.competency);assert.equal(p.source.source.status,'practice');});
