import test from 'node:test';import assert from 'node:assert/strict';
import {AIProvider,generateAI} from '../src/ai.js';import {generateGuided} from '../src/engine.js';import {stages} from '../src/schema.js';import {examples} from '../src/curriculum.js';
import {createApp} from '../src/server.js';import {openDatabase} from '../src/db.js';import {dispatch,teacher,waitJob} from './helpers.js';
const input={grade:5,subject:'Mathematics',competencyId:examples[1].id,competency:examples[1].competency,mode:'ai'};
const reply=output=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(output)}}],usage:{prompt_tokens:10,completion_tokens:20}})});
async function fixtures(){const p=await generateGuided({...input,mode:'guided',sessions:2});const parts={unpack:p.unpacking,context:p.analysis,outcomes:{sessions:p.sessions.map(({id,title,keyConcept,objectives})=>({id,title,keyConcept,objectives}))},review:p.review};for(const k of ['assessment','experiences','differentiation','ways'])parts[k]={sessions:p.sessions.map(s=>({id:s.id,[k]:s[k]}))};return parts;}
test('transient errors retry with Retry-After and retain usage for successful output',async()=>{let calls=0;const delays=[];const parts=await fixtures();const provider=new AIProvider({key:'fixture',random:()=>0,sleep:async ms=>delays.push(ms),fetchImpl:async()=>{calls++;if(calls===1)throw Error('network');if(calls===2)return {ok:false,status:429,headers:new Headers({'retry-after':'2'})};return reply(parts.unpack);}});const result=await provider.generateStructured({stage:'unpack',schema:stages.unpack,context:{},instruction:'fixture'});assert.equal(calls,3);assert.deepEqual(delays,[1000,2000]);assert.equal(result.attempts,3);assert.deepEqual(result.output,parts.unpack);});
test('provider schema rejection uses JSON compatibility and still repairs against original schema',async()=>{const parts=await fixtures();const requests=[];const provider=new AIProvider({key:'fixture',fetchImpl:async(_,o)=>{const r=JSON.parse(o.body);requests.push(r);if(requests.length===1)return {ok:false,status:400,json:async()=>({error:{message:'response_format schema is unsupported'}})};return reply(requests.length===2?{}:parts.unpack);}});const result=await provider.generateStructured({stage:'unpack',schema:stages.unpack,context:{},instruction:'fixture'});assert.equal(result.attempts,3);assert.equal(requests[1].response_format.type,'json_object');assert.match(JSON.parse(requests[2].messages[1].content).repair.issue,/required/);assert.deepEqual(result.output,parts.unpack);});
test('invalid complete-plan timing repairs the activity section without regenerating objectives',async()=>{const good=await fixtures(),bad=structuredClone(good);bad.experiences.sessions[0].experiences[0].minutes++;const calls=[];const provider=new AIProvider({key:'fixture',fetchImpl:async(_,options)=>{const {stage}=JSON.parse(JSON.parse(options.body).messages[1].content);calls.push(stage);return reply(stage==='ilawcraft'?bad:good[stage]);}});const p=await generateAI({...input,sessions:2},{provider});assert.deepEqual(calls,['ilawcraft','experiences','differentiation','review']);assert.equal(p.metadata.tokens.calls,4);assert.equal(p.metadata.tokens.input,40);assert.deepEqual(p.sessions[0].objectives,good.outcomes.sessions[0].objectives);assert.equal(p.sessions[0].experiences.reduce((n,a)=>n+a.minutes,0),45);});
test('truncated complete plan recovers through smaller stages, retains successful stages and saves an AI lesson',async()=>{const parts=await fixtures();const calls=[],progress=[];let assessmentCalls=0;const provider=new AIProvider({key:'fixture',sleep:async()=>{},fetchImpl:async(_,o)=>{const {stage}=JSON.parse(JSON.parse(o.body).messages[1].content);calls.push(stage);if(stage==='ilawcraft')return {ok:true,json:async()=>({choices:[{finish_reason:'length',message:{content:'{'}}],usage:{prompt_tokens:5,completion_tokens:6}})};if(stage==='assessment'&&++assessmentCalls===1)return {ok:false,status:503};return reply(parts[stage]);}});const storage=openDatabase(':memory:');const app=await createApp({database:storage,provider});try{const t=await teacher(app);const r=await dispatch(app,{method:'POST',url:'/api/jobs',headers:t.headers,body:{...input,sessions:2}});const job=await waitJob(app,r.json().jobId,t.headers);assert.equal(job.status,'completed',job.error);const p=(await dispatch(app,{url:`/api/plans/${job.planId}`,headers:t.headers})).json().plan;assert.equal(p.metadata.mode,'ai');assert.equal(p.metadata.aiWorkflow,'staged-recovery');assert.equal(p.metadata.tokens.calls,10);assert.equal(p.metadata.tokens.input,85);assert.equal(calls.filter(s=>s==='outcomes').length,1);assert.equal(calls.filter(s=>s==='assessment').length,2);assert.equal(p.sessions.length,2);assert.equal(p.source.competency,input.competency);}finally{storage.close();}});
test('bad keys, exhausted quota and refusal stop immediately without claiming a generated lesson',async()=>{for(const response of [{ok:false,status:401},{ok:false,status:429,json:async()=>({error:{code:'insufficient_quota'}})},{ok:true,json:async()=>({choices:[{message:{refusal:'No'}}]})}]){let calls=0;const provider=new AIProvider({key:'fixture',fetchImpl:async()=>{calls++;return response;}});await assert.rejects(()=>generateAI(input,{provider}));assert.equal(calls,1);}});
test('retry cap and long Retry-After do not loop or expose provider errors',async()=>{let calls=0;const provider=new AIProvider({key:'fixture-secret',sleep:async()=>{},fetchImpl:async()=>{calls++;return {ok:false,status:503,json:async()=>({error:{message:'fixture-secret private context'}})};}});await assert.rejects(()=>generateAI(input,{provider}),e=>!e.message.includes('fixture-secret'));assert.equal(calls,3);calls=0;provider.fetch=async()=>{calls++;return {ok:false,status:429,headers:new Headers({'retry-after':'86400'})};};await assert.rejects(()=>generateAI(input,{provider}),/rate limit/);assert.equal(calls,1);});
