import fs from 'node:fs/promises';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
import {AIProvider} from '../src/ai.js';import {generateGuided} from '../src/engine.js';import {examples} from '../src/curriculum.js';
import {createApp} from '../src/server.js';import {openDatabase} from '../src/db.js';const require=createRequire(import.meta.url);await fs.mkdir('test-results',{recursive:true});
let chromium;
let browser,page,listening=false;const errors=[];const database=openDatabase(':memory:');const aiInput={grade:5,subject:'Mathematics',competencyId:examples[1].id,competency:examples[1].competency,mode:'ai'};
const fixturePlan=await generateGuided({...aiInput,mode:'guided'});const fixtureParts={unpack:fixturePlan.unpacking,context:fixturePlan.analysis,outcomes:{sessions:fixturePlan.sessions.map(({id,title,keyConcept,objectives})=>({id,title,keyConcept,objectives}))},review:fixturePlan.review};for(const key of ['assessment','experiences','differentiation','ways'])fixtureParts[key]={sessions:fixturePlan.sessions.map(s=>({id:s.id,[key]:s[key]}))};
const aiCalls=[];let failAssessment=true,cancelNext=false;const provider=new AIProvider({key:'browser-fixture-only',sleep:async()=>{},fetchImpl:async(_,options)=>{const {stage}=JSON.parse(JSON.parse(options.body).messages[1].content);aiCalls.push(stage);if(cancelNext)return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(options.signal.reason),{once:true}));if(stage==='ilawcraft')return {ok:true,json:async()=>({choices:[{finish_reason:'length',message:{content:'{'}}]})};if(stage==='assessment'&&failAssessment){failAssessment=false;return {ok:false,status:401};}return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(fixtureParts[stage])}}]})};}});
const app=await createApp({database,provider,port:0});
try{
 try{({chromium}=require('playwright'));}catch{throw Error('Playwright is missing. Run npm install, then npm run setup:browser.');}
 const candidates=process.env.BROWSER_PATH?[process.env.BROWSER_PATH]:[chromium.executablePath(),'/usr/bin/chromium','/usr/bin/chromium-browser','/usr/bin/google-chrome'];
 let executablePath;for(const candidate of candidates){try{await fs.access(candidate);executablePath=candidate;break;}catch{}}
 if(!executablePath)throw Error(process.env.BROWSER_PATH?'BROWSER_PATH does not point to an existing executable.':'Chromium is missing. Run npm run setup:browser or set BROWSER_PATH to an installed Chromium executable.');
 browser=await chromium.launch({...(executablePath===chromium.executablePath()?{}:{executablePath}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 // Real loopback HTTP avoids interception-header deadlocks and exercises browser cookies/compression.
 const address=await app.listen();listening=true;const baseURL=`http://127.0.0.1:${address.port}`;
 app.server.on('request',(req,res)=>{console.log('HTTP request',req.method,req.url);res.on('finish',()=>console.log('HTTP complete',req.url,res.statusCode));});
 const probe=await fetch(baseURL,{signal:AbortSignal.timeout(10000)});console.log('HTTP probe',probe.status,probe.headers.get('content-type'));assert.equal(probe.status,200);assert.match(probe.headers.get('content-type'),/text\/html/);await probe.text();
 page=await context.newPage();page.on('response',r=>{if(r.url()===baseURL+'/')console.log('Navigation response',r.status(),r.headers());});page.on('requestfailed',r=>console.log('Request failed',r.url(),r.failure()));page.on('download',d=>console.log('Download',d.suggestedFilename()));page.on('pageerror',e=>errors.push(e.message));await page.goto(baseURL);
 await page.getByLabel('Display name').fill('Teacher');await page.getByLabel('Email address').fill('browser@example.test');await page.getByLabel('Password',{exact:true}).fill('browser test password 123');await page.getByRole('button',{name:'Create teacher account'}).click();await page.getByRole('heading',{name:'Your lesson workspace'}).waitFor();
 await page.getByRole('button',{name:/Adding unlike fractions/}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('heading',{name:'Choose the learning'}).waitFor();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.locator('input[name=mode][value=guided]').check();await page.getByRole('button',{name:'Create guided draft'}).click();
 await page.getByRole('heading',{name:'I — Intentions'}).waitFor({timeout:20000});await page.getByLabel('Success criterion').fill('Teacher criterion: accurate fractions and justified equal-whole model.');await page.getByText('Saved to your workspace',{exact:true}).waitFor();
 await page.getByRole('button',{name:/L Learning Experiences/}).click();await page.getByRole('button',{name:'Low-resource',exact:true}).nth(2).click();await page.getByRole('button',{name:'Revise',exact:true}).click();await page.getByRole('button',{name:/I Intentions/}).click();assert.match(await page.getByLabel('Success criterion').inputValue(),/Teacher criterion/);
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'Unintended horizontal overflow');
 const missingLabels=await page.evaluate(()=>[...document.querySelectorAll('input:not([type=hidden]),select,textarea')].filter(el=>!el.labels?.length&&!el.getAttribute('aria-label')).length);assert.equal(missingLabels,0);
 await page.getByRole('button',{name:'Export',exact:true}).click();const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download DOCX'}).click()]);await download.saveAs('test-results/browser-export.docx');
 const [pdfDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download PDF'}).click()]);await pdfDownload.saveAs('test-results/browser-export.pdf');assert.match((await fs.readFile('test-results/browser-export.pdf')).subarray(0,8).toString(),/%PDF-1.7/);assert.deepEqual(errors,[]);
 await page.getByRole('button',{name:'Close',exact:true}).click();
 const me=await (await context.request.get(`${baseURL}/api/me`)).json();
 const created=await context.request.post(`${baseURL}/api/jobs`,{headers:{'x-csrf-token':me.csrf,origin:baseURL},data:aiInput});assert.equal(created.status(),202);const {jobId}=await created.json();
 await page.goto(`${baseURL}/#generation/${jobId}`);await page.getByRole('button',{name:'Resume generation',exact:true}).waitFor({timeout:20000});await page.reload();await page.getByRole('button',{name:'Resume generation',exact:true}).click();await page.getByRole('heading',{name:'I — Intentions'}).waitFor({timeout:20000});
 assert.equal(aiCalls.filter(s=>s==='unpack').length,1);assert.equal(aiCalls.filter(s=>s==='outcomes').length,1);assert.equal(database.db.prepare('SELECT count(*) n FROM plans').get().n,2);assert.deepEqual(errors,[]);await page.screenshot({path:'test-results/ai-resumed.png',fullPage:true});
 cancelNext=true;const cancelling=await context.request.post(`${baseURL}/api/jobs`,{headers:{'x-csrf-token':me.csrf,origin:baseURL},data:aiInput});assert.equal(cancelling.status(),202);const cancelledId=(await cancelling.json()).jobId;await page.goto(`${baseURL}/#generation/${cancelledId}`);await page.getByRole('button',{name:'Cancel generation',exact:true}).click();await page.getByText('Generation stopped. You can review the input or resume retained stages.',{exact:true}).waitFor();assert.equal(database.db.prepare('SELECT status FROM jobs WHERE id=?').get(cancelledId).status,'cancelled');assert.equal(database.db.prepare('SELECT count(*) n FROM plans').get().n,2);

 await fs.writeFile('test-results/browser-status.json',JSON.stringify({status:'passed',desktop:'1440×1000',mobile:'390×844',journey:'account, guided generation, autosave, targeted revision, DOCX/PDF downloads, synthetic AI truncation recovery, retained-stage resume after reload, cancellation',accessibility:'labels and horizontal overflow only; not full WCAG audit'},null,2));console.log('Browser journey passed.');
}catch(e){if(page)try{await page.screenshot({path:'test-results/browser-failure.png',fullPage:true,timeout:5000});}catch{}await fs.writeFile('test-results/browser-status.json',JSON.stringify({status:'blocked-or-failed',reason:e.message.slice(0,1500),pageErrors:errors},null,2));console.error('Browser verification did not complete:',e.message.slice(0,400));process.exitCode=1;}
finally{if(browser)await browser.close();if(listening)await app.close();database.close();}
