import {encodePNG} from '../src/images.js';
import fs from 'node:fs/promises';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
import {AIProvider} from '../src/ai.js';import {generateGuided} from '../src/engine.js';import {examples} from '../src/curriculum.js';
import {createApp} from '../src/server.js';import {openDatabase} from '../src/db.js';const require=createRequire(import.meta.url);await fs.mkdir('test-results',{recursive:true});
let chromium;
let browser,page,listening=false;const errors=[];const database=openDatabase(':memory:');const aiInput={grade:5,subject:'Mathematics',competencyId:examples[1].id,competency:examples[1].competency,mode:'ai'};
const fixturePlan=await generateGuided({...aiInput,mode:'guided'});const fixtureParts={unpack:fixturePlan.unpacking,context:fixturePlan.analysis,outcomes:{sessions:fixturePlan.sessions.map(({id,title,keyConcept,objectives})=>({id,title,keyConcept,objectives}))},review:fixturePlan.review};for(const key of ['assessment','experiences','differentiation','ways'])fixtureParts[key]={sessions:fixturePlan.sessions.map(s=>({id:s.id,[key]:s[key]}))};
const weeklyPlan=await generateGuided({...aiInput,mode:'guided',sessions:5});const weeklyParts={unpack:weeklyPlan.unpacking,context:weeklyPlan.analysis,outcomes:{sessions:weeklyPlan.sessions.map(({id,title,keyConcept,objectives})=>({id,title,keyConcept,objectives}))},review:weeklyPlan.review};for(const s of weeklyPlan.sessions)weeklyParts[`session_${s.id}`]=Object.fromEntries(['id','assessment','experiences','differentiation','ways'].map(k=>[k,s[k]]));
const aiCalls=[];let failAssessment=true,cancelNext=false,useWeeklyFixture=false;const provider=new AIProvider({key:'browser-fixture-only',sleep:async()=>{},fetchImpl:async(_,options)=>{const {stage}=JSON.parse(JSON.parse(options.body).messages[1].content);aiCalls.push(stage);if(cancelNext)return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(options.signal.reason),{once:true}));if(stage==='ilawcraft')return {ok:true,json:async()=>({choices:[{finish_reason:'length',message:{content:'{'}}]})};if(stage==='assessment'&&failAssessment){failAssessment=false;return {ok:false,status:401};}return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify((useWeeklyFixture?weeklyParts:fixtureParts)[stage])}}]})};}});
const app=await createApp({database,provider,port:0});
try{
 try{({chromium}=require('playwright'));}catch{throw Error('Playwright is missing. Run npm install, then npm run setup:browser.');}
 const candidates=process.env.BROWSER_PATH?[process.env.BROWSER_PATH]:[chromium.executablePath(),'/usr/bin/chromium','/usr/bin/chromium-browser','/usr/bin/google-chrome'];
 let executablePath;for(const candidate of candidates){try{await fs.access(candidate);executablePath=candidate;break;}catch{}}
 if(!executablePath)throw Error(process.env.BROWSER_PATH?'BROWSER_PATH does not point to an existing executable.':'Chromium is missing. Run npm run setup:browser or set BROWSER_PATH to an installed Chromium executable.');
 browser=await chromium.launch({...(executablePath===chromium.executablePath()?{}:{executablePath}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 // Real loopback HTTP avoids interception-header deadlocks and exercises browser cookies/compression.
 const address=await app.listen();listening=true;const baseURL=`http://127.0.0.1:${address.port}`;
 app.server.on('request',(req,res)=>{console.log('HTTP request',req.method,req.url);res.on('finish',()=>console.log('HTTP complete',req.url,res.statusCode));});
 const probe=await fetch(baseURL,{signal:AbortSignal.timeout(10000)});console.log('HTTP probe',probe.status,probe.headers.get('content-type'));assert.equal(probe.status,200);assert.match(probe.headers.get('content-type'),/text\/html/);await probe.text();
 page=await context.newPage();page.on('response',r=>{if(r.url()===baseURL+'/')console.log('Navigation response',r.status(),r.headers());});page.on('requestfailed',r=>console.log('Request failed',r.url(),r.failure()));page.on('download',d=>console.log('Download',d.suggestedFilename()));page.on('pageerror',e=>errors.push(e.message));await page.goto(baseURL);
 await page.getByLabel('Display name').fill('Teacher');await page.getByLabel('Email address').fill('browser@example.test');await page.getByLabel('Password',{exact:true}).fill('browser test password 123');await page.getByRole('button',{name:'Create teacher account'}).click();await page.getByRole('heading',{name:'Your lesson workspace'}).waitFor();
 await page.getByRole('button',{name:/Adding unlike fractions/}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('heading',{name:'Choose the learning'}).waitFor();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.locator('input[name=mode][value=guided]').check();await page.getByRole('button',{name:'Create guided draft'}).click();
 await page.getByRole('heading',{name:'I — Intentions'}).waitFor({timeout:20000});await page.getByLabel('Success criterion').fill(String.raw`Teacher criterion: accurate fractions and justified equal-whole model: \(\frac{1}{2}+\frac{1}{4}\).`);await page.getByText('Saved to your workspace',{exact:true}).waitFor();
 await page.getByRole('button',{name:/L Learning Experiences/}).click();await page.getByRole('button',{name:'Low-resource',exact:true}).nth(2).click();await page.getByRole('button',{name:'Revise',exact:true}).click();await page.getByRole('button',{name:'Accept proposed revision',exact:true}).click();await page.getByRole('button',{name:/I Intentions/}).click();assert.match(await page.getByLabel('Success criterion').inputValue(),/Teacher criterion/);
 assert.ok(await page.locator('math mfrac').count()>0,'Native MathML fraction preview');
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'Unintended horizontal overflow');
 const missingLabels=await page.evaluate(()=>[...document.querySelectorAll('input:not([type=hidden]),select,textarea')].filter(el=>!el.labels?.length&&!el.getAttribute('aria-label')).length);assert.equal(missingLabels,0);
 await page.getByRole('button',{name:'Export',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Download PowerPoint'}).isDisabled(),true);const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download DOCX'}).click()]);await download.saveAs('test-results/browser-export.docx');
 const [pdfDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download PDF'}).click()]);await pdfDownload.saveAs('test-results/browser-export.pdf');assert.match((await fs.readFile('test-results/browser-export.pdf')).subarray(0,8).toString(),/%PDF-1.7/);assert.deepEqual(errors,[]);
 await page.getByRole('button',{name:'Close',exact:true}).click();
 const me=await (await context.request.get(`${baseURL}/api/me`)).json();
 const savedId=page.url().split('/').at(-1);const saved=(await (await context.request.get(`${baseURL}/api/plans/${savedId}`)).json()).plan;
 const reviewed=await context.request.post(`${baseURL}/api/plans/${savedId}/review`,{headers:{'x-csrf-token':me.csrf,origin:baseURL},data:{revision:saved.revision,confirm:true}});assert.equal(reviewed.status(),200);await page.reload();await page.getByRole('heading',{name:'I — Intentions'}).waitFor();await page.getByRole('button',{name:'Export',exact:true}).click();const [pptxDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download PowerPoint'}).click()]);await pptxDownload.saveAs('test-results/browser-export.pptx');assert.match(pptxDownload.suggestedFilename(),/\.pptx$/);assert.equal((await fs.readFile('test-results/browser-export.pptx')).subarray(0,2).toString(),'PK');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Check arithmetic',exact:true}).click();await page.getByLabel('Expression',{exact:true}).fill(String.raw`\frac{1}{2}+\frac{1}{4}=\frac{3}{4}`);await page.getByRole('button',{name:'Check expression',exact:true}).click();await page.getByText(/Arithmetic agrees: 3\/4/).waitFor();await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Images',exact:true}).click();await page.getByLabel('Lesson image file').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:encodePNG(32,16,Buffer.alloc(32*16*3,120))});await page.getByLabel('Caption',{exact:true}).fill('Native image fixture');await page.getByLabel('Alternative text',{exact:true}).fill('Gray rectangular fixture');await page.getByLabel('Rights / source',{exact:true}).fill('Teacher-created test fixture');await page.getByRole('button',{name:'Upload image',exact:true}).click();await page.getByRole('button',{name:'Link to selected target',exact:true}).click();await page.getByRole('button',{name:'Unlink from lesson',exact:true}).waitFor();await page.getByRole('button',{name:'Create coordinate diagram',exact:true}).click();await page.getByRole('button',{name:'Preview coordinate diagram',exact:true}).click();await page.screenshot({path:'test-results/coordinate-diagram.png',fullPage:true});await page.getByRole('button',{name:'Save diagram image',exact:true}).click();await page.getByRole('button',{name:'Edit diagram source',exact:true}).waitFor();await page.getByRole('button',{name:'Link to selected target',exact:true}).click();await page.getByRole('button',{name:'Close',exact:true}).click();
 let latest=(await (await context.request.get(`${baseURL}/api/plans/${savedId}`)).json()).plan;assert.equal((await context.request.post(`${baseURL}/api/plans/${savedId}/review`,{headers:{'x-csrf-token':me.csrf,origin:baseURL},data:{revision:latest.revision,confirm:true}})).status(),200);await page.reload();await page.getByRole('heading',{name:'I — Intentions'}).waitFor();await page.getByRole('button',{name:'Edit slides',exact:true}).click();await page.getByLabel('Slide 1 title',{exact:true}).fill('Native teacher slide edit');await page.locator('details').filter({has:page.getByLabel(/Show the accepted answer after slide/)}).first().locator('summary').click();await page.getByLabel(/Show the accepted answer after slide/).first().check();await page.getByRole('button',{name:'Save slide edits',exact:true}).click();await page.getByText('Slide edits saved. PowerPoint will use this storyboard.',{exact:true}).waitFor();await page.screenshot({path:'test-results/slide-editor.png',fullPage:true});await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByLabel('Lesson title',{exact:true}).fill('Native title after slide edit');await page.getByText('Saved to your workspace',{exact:true}).waitFor();latest=(await (await context.request.get(`${baseURL}/api/plans/${savedId}`)).json()).plan;assert.equal((await context.request.get(`${baseURL}/api/plans/${savedId}/pptx`)).status(),409);assert.equal((await context.request.post(`${baseURL}/api/plans/${savedId}/review`,{headers:{'x-csrf-token':me.csrf,origin:baseURL},data:{revision:latest.revision,confirm:true}})).status(),200);await page.reload();await page.getByRole('heading',{name:'I — Intentions'}).waitFor();await page.getByRole('button',{name:'Edit slides',exact:true}).click();await page.getByRole('heading',{name:'Slides need an update',exact:true}).waitFor();await page.getByRole('button',{name:'Rebuild from reviewed lesson',exact:true}).click();await page.getByLabel('Slide 1 title',{exact:true}).waitFor();await page.getByRole('button',{name:'Close',exact:true}).click();
 const recoveredKeys=await page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('ilaw-device-recovery',1);r.onsuccess=()=>{const q=r.result.transaction('drafts').objectStore('drafts').getAllKeys();q.onsuccess=()=>{resolve(q.result.length);r.result.close();};q.onerror=()=>reject(q.error);};r.onerror=()=>reject(r.error);}));assert.ok(recoveredKeys>0);const [draftDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Draft backup',exact:true}).click()]);await draftDownload.saveAs('test-results/browser-draft.json');assert.equal(JSON.parse(await fs.readFile('test-results/browser-draft.json','utf8')).kind,'ilaw-device-draft');assert.deepEqual(errors,[]);
 const created=await context.request.post(`${baseURL}/api/jobs`,{headers:{'x-csrf-token':me.csrf,origin:baseURL},data:aiInput});assert.equal(created.status(),202);const {jobId}=await created.json();
 await page.goto(`${baseURL}/#generation/${jobId}`);await page.getByRole('button',{name:'Resume generation',exact:true}).waitFor({timeout:20000});const [diagnosticDownload]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download diagnostic summary',exact:true}).click()]);await diagnosticDownload.saveAs('test-results/browser-diagnostics.json');const diagnosticText=await fs.readFile('test-results/browser-diagnostics.json','utf8');assert.ok(!diagnosticText.includes('browser-fixture-only'));assert.ok(JSON.parse(diagnosticText).events.length>0);await page.reload();await page.getByRole('button',{name:'Resume generation',exact:true}).click();await page.getByRole('heading',{name:'I — Intentions'}).waitFor({timeout:20000});
 assert.equal(aiCalls.filter(s=>s==='unpack').length,1);assert.equal(aiCalls.filter(s=>s==='outcomes').length,1);assert.equal(database.db.prepare('SELECT count(*) n FROM plans').get().n,2);assert.deepEqual(errors,[]);await page.screenshot({path:'test-results/ai-resumed.png',fullPage:true});
 cancelNext=true;const cancelling=await context.request.post(`${baseURL}/api/jobs`,{headers:{'x-csrf-token':me.csrf,origin:baseURL},data:aiInput});assert.equal(cancelling.status(),202);const cancelledId=(await cancelling.json()).jobId;await page.goto(`${baseURL}/#generation/${cancelledId}`);await page.getByRole('button',{name:'Cancel generation',exact:true}).click();await page.getByText('Generation stopped. You can review the input or resume retained stages.',{exact:true}).waitFor();assert.equal(database.db.prepare('SELECT status FROM jobs WHERE id=?').get(cancelledId).status,'cancelled');assert.equal(database.db.prepare('SELECT count(*) n FROM plans').get().n,2);

 cancelNext=false;useWeeklyFixture=true;const weeklyCreated=await context.request.post(`${baseURL}/api/jobs`,{headers:{'x-csrf-token':me.csrf,origin:baseURL},data:{...aiInput,sessions:5}});assert.equal(weeklyCreated.status(),202);const weeklyId=(await weeklyCreated.json()).jobId;await page.goto(`${baseURL}/#generation/${weeklyId}`);await page.getByRole('heading',{name:'I — Intentions'}).waitFor({timeout:20000});const weeklyJob=await (await context.request.get(`${baseURL}/api/jobs/${weeklyId}`)).json();assert.equal(weeklyJob.status,'completed');const weeklySaved=(await (await context.request.get(`${baseURL}/api/plans/${weeklyJob.planId}`)).json()).plan;assert.equal(weeklySaved.sessions.length,5);assert.equal(weeklySaved.metadata.aiWorkflow,'session-adaptive');assert.equal(weeklyJob.usage.calls,9);assert.equal(database.db.prepare('SELECT count(*) n FROM plans').get().n,3);assert.deepEqual(errors,[]);await page.screenshot({path:'test-results/weekly-ai.png',fullPage:true});
 await fs.writeFile('test-results/browser-status.json',JSON.stringify({status:'passed',desktop:'1440×1000',mobile:'390×844',journey:'account, guided generation, autosave, targeted revision, MathML preview, DOCX/PDF/PPTX downloads, owned image upload/linking, exact arithmetic, edited/stale slide recovery, IndexedDB and draft download, synthetic AI truncation recovery, retained-stage resume after reload, owned diagnostic download, cancellation, five-session adaptive AI drafting',accessibility:'labels and horizontal overflow only; not full WCAG audit'},null,2));console.log('Browser journey passed.');
}catch(e){if(page)try{await page.screenshot({path:'test-results/browser-failure.png',fullPage:true,timeout:5000});}catch{}await fs.writeFile('test-results/browser-status.json',JSON.stringify({status:'blocked-or-failed',reason:e.message.slice(0,1500),pageErrors:errors},null,2));console.error('Browser verification did not complete:',e.message.slice(0,400));process.exitCode=1;}
finally{if(browser)await browser.close();if(listening)await app.close();database.close();}
