import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../src/server.js';import {openDatabase} from '../src/db.js';import {clientHarness} from './dom-harness.js';
test('teacher UI creates a protected observation, saves factual notes and records reflection',async()=>{
 const db=openDatabase(':memory:'),app=await createApp({database:db});const c=await clientHarness(app);try{c.field('Display name').value='Teacher';c.field('Email address').value='observation-ui@example.test';c.field('Password').value='long observation UI password';await c.document.querySelector('form').emit('submit');await c.flush();await c.api.newLesson(c.api.state.records.find(r=>r.id==='math-5'));await c.flush();for(let i=0;i<5;i++)await c.document.querySelector('#wizard-form').emit('submit');for(let i=0;i<150&&c.api.state.view!=='plan';i++)await c.flush();
  await c.button('Actual reflection').emit('click');const observed=c.field('Actual evidence of learning');observed.value='Learners explained equivalent parts.';await observed.emit('input');await c.document.querySelector('#modal-root form').emit('submit');assert.equal(c.api.state.plan.reflections.s1.observedEvidence,'Learners explained equivalent parts.');
  await c.button('Observation').emit('click');const focus=c.field('Which part of learning should we look at?');focus.value='Explanations of equal wholes.';await focus.emit('input');await c.document.querySelector('#modal-root form').emit('submit');await c.flush();assert.equal(c.api.state.view,'observation');assert.ok(c.document.textContent.includes('Lesson revision'));
  const note=c.field('Factual note');note.value='Two groups compared equal-size fraction bars.';await note.emit('input');await c.document.querySelector('form').emit('submit');assert.ok(c.document.textContent.includes('Two groups compared equal-size fraction bars.'));await c.button('Finalize record').emit('click');assert.ok(c.button('Reopen for amendment'));assert.ok(!c.field('Factual note'));
 }finally{c.api.closeModal();db.close();}
});
test('client boot, real account flow, progressive form, generation route, edits, autosave, targeted revision and export controls',async()=>{
 const db=openDatabase(':memory:');const app=await createApp({database:db});let c;
 try{
  c=await clientHarness(app);assert.ok(c.document.textContent.includes('Create your workspace'));
  c.field('Display name').value='Teacher';c.field('Email address').value='client@example.test';c.field('Password').value='a long client password';await c.document.querySelector('form').emit('submit');await c.flush();assert.ok(c.document.textContent.includes('Your lesson workspace'));
  const r=c.api.state.records.find(r=>r.id==='math-5');await c.api.newLesson(r);await c.flush();assert.ok(c.document.textContent.includes('Your class'));
  for(let i=0;i<4;i++){await c.document.querySelector('#wizard-form').emit('submit');await c.flush();assert.equal(c.api.state.step,i+1);}
  await c.document.querySelector('#wizard-form').emit('submit');
  for(let i=0;i<150&&c.api.state.view!=='plan';i++)await c.flush();assert.equal(c.api.state.view,'plan');assert.ok(c.document.textContent.includes('I — Intentions'));
  const criterion=c.field('Success criterion');criterion.value='Teacher custom criterion: accurate sum and justified model.';await criterion.emit('input');assert.equal(c.api.state.dirty,true);await c.api.saveNow();assert.equal(c.api.state.dirty,false);assert.ok(c.api.state.plan.revision>1);
  const before=c.api.state.plan.sessions[0].objectives[0].criterion;c.api.state.section='experiences';c.api.renderEditor();assert.ok(c.field('Teacher role'));
  c.api.confirmRegenerate('s1','experiences','s1-l3','low-resource');await c.button('Revise').emit('click');await c.flush();assert.equal(c.api.state.plan.sessions[0].objectives[0].criterion,before);
  await c.api.showExport();assert.ok(c.document.querySelector('a[href]'));assert.ok(c.document.textContent.includes('Download DOCX'));await c.button('Download DOCX').emit('click');assert.match(c.document.downloads[0].download,/\.docx$/);await c.button('Download PDF').emit('click');assert.match(c.document.downloads[1].download,/\.pdf$/);assert.ok(c.document.textContent.includes('browser has received the download'));c.api.closeModal();
  await c.api.showVersions();assert.ok(c.document.textContent.includes('Guided revision: experiences component'));c.api.closeModal();
  await c.api.reviewPlan();const checkbox=c.document.querySelector('#modal-root input');checkbox.checked=true;await checkbox.emit('change');await c.button('Record teacher review').emit('click');assert.equal(c.api.state.plan.metadata.status,'reviewed');
 }finally{if(c)c.api.closeModal();db.close();}
});
test('UI evidence recording uses counts without learner identity fields',async()=>{
 const db=openDatabase(':memory:');const app=await createApp({database:db});const c=await clientHarness(app);try{c.field('Display name').value='Teacher';c.field('Email address').value='evidence@example.test';c.field('Password').value='long evidence password';await c.document.querySelector('form').emit('submit');await c.flush();await c.api.newLesson(c.api.state.records.find(r=>r.id==='math-5'));await c.flush();c.api.state.input.sessions=2;for(let i=0;i<5;i++)await c.document.querySelector('#wizard-form').emit('submit');for(let i=0;i<150&&c.api.state.view!=='plan';i++)await c.flush();await c.button('Record evidence').emit('click');c.field('Needs prerequisite support').value=10;await c.field('Needs prerequisite support').emit('input');c.field('Partial mastery / reinforcement').value=15;await c.field('Partial mastery / reinforcement').emit('input');c.field('Meets the success criterion').value=10;await c.field('Meets the success criterion').emit('input');c.field('Ready for extension').value=5;await c.field('Ready for extension').emit('input');await c.document.querySelector('#modal-root form').emit('submit');assert.equal(c.api.state.plan.evidenceSummary.s1.support,10);c.api.state.session=1;c.api.renderEditor();assert.ok(c.document.textContent.includes('Evidence from Session 1'));assert.ok(!c.document.querySelector('input[name="learnerName"]'));const reopened=await clientHarness(app,{cookie:c.sessionCookie(),hash:`#plan/${c.api.state.plan.id}`});assert.equal(reopened.api.state.view,'plan');assert.ok(reopened.document.textContent.includes('Evidence recorded for this session'));reopened.api.closeModal();}finally{c.api.closeModal();db.close();}
});
test('planning protects drafts, prevents skipped steps, and restores account AI settings safely',async()=>{
 const db=openDatabase(':memory:');const app=await createApp({database:db});const c=await clientHarness(app);try{
 c.field('Display name').value='Teacher';c.field('Email address').value='usability@example.test';c.field('Password').value='long usability password';await c.document.querySelector('form').emit('submit');await c.flush();
 await c.api.newLesson(c.api.state.records.find(r=>r.id==='math-5'));await c.flush();
 assert.ok(c.document.querySelector('details.document-details'));const designStep=c.document.querySelectorAll('.step').at(-1);assert.equal(designStep.disabled,true);
 await c.api.newLesson();assert.ok(c.document.textContent.includes('Start a new lesson?'));assert.equal(c.api.state.input.competencyId,'math-5');await c.button('Keep planning').emit('click');await c.flush();
 const nav=c.document.querySelectorAll('.navbtn').find(n=>n.attrs['aria-label']==='AI settings');await nav.emit('click');await c.flush();
 assert.ok(c.field('API key'));assert.equal(c.field('API key').attrs.type,'password');c.field('API key').value='test-groq-key-123456789';c.field('AI provider').value='groq';await c.document.querySelector('form').emit('submit');await c.flush();assert.ok(c.document.textContent.includes('Groq key saved'));assert.equal(c.field('API key').value,'');
 await c.button('Sign out').emit('click');await c.flush();assert.equal(c.api.state.input,null);assert.equal(c.api.state.plan,null);assert.equal(c.api.state.records.length,0);
 }finally{c.api.closeModal();db.close();}
});
