import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {PGlite} from '@electric-sql/pglite';import {cloudClient} from '../spikes/free-cloud/client.js';
test('cloud pilot SQL enforces anonymous/other-owner isolation, immutable history and optimistic saves in PostgreSQL WASM',async()=>{
 const db=new PGlite();const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333';
 try{await db.exec(`create role authenticated; create role anon; create schema auth; create table auth.users(id uuid primary key); insert into auth.users values('${a}'),('${b}'); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;`);await db.exec(fs.readFileSync('spikes/free-cloud/schema.sql','utf8'));
 const actor=async(role,user='')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec(`set role ${role}`);};const save=(revision,title)=>db.query('select public.ilaw_save_plan($1,$2,$3::jsonb) payload',[id,revision,JSON.stringify({id,schemaVersion:1,title})]);
 await actor('authenticated',a);assert.equal((await save(0,'First')).rows[0].payload.revision,1);assert.equal((await save(1,'Second')).rows[0].payload.revision,2);await assert.rejects(save(1,'Stale'),/Revision conflict/);await assert.rejects(db.query('update public.ilaw_cloud_plans set revision=8'),/permission denied/);assert.equal((await db.query('select * from public.ilaw_cloud_revisions')).rows.length,2);
 await actor('authenticated',b);assert.equal((await db.query('select * from public.ilaw_cloud_plans')).rows.length,0);assert.equal((await db.query('select * from public.ilaw_cloud_revisions')).rows.length,0);await assert.rejects(save(2,'Other owner'),/Plan not found/);await actor('anon');await assert.rejects(save(2,'Anonymous'),/permission denied/);await assert.rejects(db.query('select * from public.ilaw_cloud_plans'),/permission denied/);
 await actor('authenticated',a);assert.equal((await db.query('select payload from public.ilaw_cloud_plans')).rows[0].payload.title,'Second');await assert.rejects(db.query('delete from public.ilaw_cloud_revisions'),/permission denied/);
 }finally{await db.close();}
});
test('cloud adapter uses user bearer token, preserves conflict status and never supplies an owner override',async()=>{let request;const client=cloudClient({url:'https://fixture.supabase.co',publishableKey:'publishable-fixture',accessToken:'user-fixture',fetchImpl:async(url,options)=>{request={url,options};return {ok:false,status:409,json:async()=>({code:'40001'})};}});await assert.rejects(client.save({id:'fixture',schemaVersion:1},3),e=>e.code==='40001');assert.equal(request.options.headers.Authorization,'Bearer user-fixture');assert.ok(!JSON.parse(request.options.body).owner_id);});
