import test from 'node:test';import assert from 'node:assert/strict';import {GeminiBackgroundClient} from '../spikes/gemini-background/client.js';
const schema={type:'object',properties:{task:{type:'string',minLength:1}},required:['task'],additionalProperties:false};
const completed={id:'native_fixture',status:'completed',steps:[{type:'model_output',content:[{type:'text',text:'{"task":"Actual task fixture"}'}]}],usage:{total_input_tokens:12,total_output_tokens:20,total_thought_tokens:8}};
const response=body=>({ok:true,json:async()=>body});
test('background prototype is disabled by default',async()=>{const c=new GeminiBackgroundClient({key:'fixture',fetchImpl:async()=>{throw Error('must not call');}});await assert.rejects(()=>c.run({prompt:'fixture',schema}),/opt-in/);});
test('background ID is retained before polling and resume does not create a second interaction',async()=>{const calls=[];let state,fail=true;const c=new GeminiBackgroundClient({enabled:true,key:'fixture',sleep:async()=>{},fetchImpl:async(url,o)=>{calls.push(o.method+' '+url.split('/').at(-1));if(o.method==='POST'){const b=JSON.parse(o.body);assert.equal(b.background,true);assert.equal(b.response_format.mime_type,'application/json');return response({id:'native_fixture',status:'in_progress'});}if(fail)return {ok:false,status:503};return response(completed);}});await assert.rejects(()=>c.run({prompt:'private fixture',schema,onState:async s=>state=s}),/503/);assert.ok(state.id);assert.ok(!JSON.stringify(state).includes('private fixture'));fail=false;const result=await c.run({prompt:'private fixture',schema,state});assert.equal(calls.filter(s=>s.startsWith('POST')).length,1);assert.equal(result.output.task,'Actual task fixture');assert.deepEqual(result.usage,{input:12,output:20,thinking:8});await assert.rejects(()=>c.run({prompt:'changed',schema,state}),/different input/);});
test('background polling is bounded and cleanup routes are explicit',async()=>{const calls=[];const c=new GeminiBackgroundClient({enabled:true,key:'fixture',maxPolls:2,sleep:async()=>{},fetchImpl:async(url,o)=>{calls.push(o.method+' '+url);return response({id:'native_fixture',status:'in_progress'});}});await assert.rejects(()=>c.run({prompt:'fixture',schema}),/polling limit/);assert.equal(calls.length,3);await c.cancel('native_fixture');await c.remove('native_fixture');assert.ok(calls.at(-2).endsWith('/cancel'));assert.ok(calls.at(-1).startsWith('DELETE'));await assert.rejects(()=>c.remove('../private'),/Invalid/);});
test('background schema violations cannot become accepted lesson content',async()=>{const c=new GeminiBackgroundClient({enabled:true,key:'fixture',fetchImpl:async()=>response({...completed,steps:[{type:'model_output',content:[{type:'text',text:'{"task":"","extra":"untrusted"}'}]}]})});await assert.rejects(()=>c.run({prompt:'fixture',schema}));});
test('background cancellation propagates to remote cancellation',async()=>{const controller=new AbortController();const calls=[];const c=new GeminiBackgroundClient({enabled:true,key:'fixture',sleep:async()=>controller.abort(),fetchImpl:async(url,o)=>{calls.push(url);return response({id:'native_fixture',status:'in_progress'});}});await assert.rejects(()=>c.run({prompt:'fixture',schema,signal:controller.signal}));assert.ok(calls.at(-1).endsWith('/cancel'));});
