import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {policySnapshot,loadPolicy} from '../src/policy.js';import {generateGuided} from '../src/engine.js';import {examples} from '../src/curriculum.js';
test('unconfigured policy is explicitly unverified',()=>{assert.equal(policySnapshot().status,'unverified');assert.equal(policySnapshot().sources.length,0);});
test('operator policy is versioned, scoped, snapshotted and never an automatic-compliance claim',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ilaw-policy-'));const file=path.join(dir,'registry.json');const fixture={status:'operator-reviewed',policyVersion:'TEST-FIXTURE-NOT-REAL-POLICY',verifiedAt:'2026-09-30',effectiveFrom:'2020-01-01',gradeScope:[5],sections:{assessment:'Assessment'},sources:[{url:'https://www.deped.gov.ph/',issuance:'Synthetic test fixture, not an issuance',date:'2026-09-30',section:'Fixture section',excerpt:'Fixture excerpt, not official guidance.',interpretation:'Used only to test the registry plumbing.',behavior:'No official policy asserted by this fixture.',reviewer:'Test runner'}]};
 fs.writeFileSync(file,JSON.stringify(fixture));process.env.ILAW_POLICY_FILE=file;try{
 assert.equal(policySnapshot({grade:5}).status,'operator-reviewed');assert.equal(policySnapshot({grade:7}).status,'unverified');const r=examples[1];const p=await generateGuided({grade:5,subject:r.subject,competencyId:r.id,competency:r.competency});assert.equal(p.metadata.policyVersion,fixture.policyVersion);assert.equal(p.policy.sections.assessment,'Assessment');assert.ok(p.quality.checks.some(c=>c.code==='policy-registry'));assert.ok(p.policy.notice.includes('not automatic compliance'));assert.equal(p.source.source.status,'practice');
 fixture.effectiveTo='2020-02-01';fs.writeFileSync(file,JSON.stringify(fixture));assert.equal(policySnapshot({grade:5}).status,'unverified');
 }finally{delete process.env.ILAW_POLICY_FILE;fs.rmSync(dir,{recursive:true});}
});
test('unreviewed or non-authoritative policy registries fail closed',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ilaw-bad-policy-'));const file=path.join(dir,'registry.json');fs.writeFileSync(file,JSON.stringify({status:'generated-by-ai',policyVersion:'invented',verifiedAt:'2026-09-30',sources:[]}));process.env.ILAW_POLICY_FILE=file;try{assert.throws(()=>loadPolicy(),/operator review/);}finally{delete process.env.ILAW_POLICY_FILE;fs.rmSync(dir,{recursive:true});}});
