import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {generateAI,AIProvider} from '../src/ai.js';import {generateGuided} from '../src/engine.js';import {examples} from '../src/curriculum.js';import {openDatabase} from '../src/db.js';import {createApp} from '../src/server.js';import {teacher,dispatch,waitJob} from './helpers.js';
const input={grade:5,subject:'Mathematics',competencyId:examples[1].id,competency:examples[1].competency,mode:'ai',aiWorkflow:'staged'};
async function fixture(){const p=await generateGuided({...input,mode:'guided'});const parts={unpack:p.unpacking,context:p.analysis,outcomes:{sessions:p.sessions.map(({id,title,keyConcept,objectives})=>({id,title,keyConcept,objectives}))},review:p.review};for(const k of ['assessment','experiences','differentiation','ways'])parts[k]={sessions:p.sessions.map(s=>({id:s.id,[k]:s[k]}))};return parts;}
function providerFor(parts,calls,fail){return new AIProvider({key:'fixture',sleep:async()=>{},fetchImpl:async(_,o)=>{const {stage}=JSON.parse(JSON.parse(o.body).messages[1].content);calls.push(stage);if(fail(stage))return {ok:false,status:401};return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify(parts[stage])}}],usage:{prompt_tokens:10,completion_tokens:20}})};}});}
test('failed staged job survives database reopen, resumes validated stages and saves once',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ilaw-retention-'));const file=path.join(dir,'db');const parts=await fixture(),calls=[];let fail=true,storage=openDatabase(file);let app=await createApp({database:storage,provider:providerFor(parts,calls,s=>fail&&s==='assessment')});try{const t=await teacher(app);const response=await dispatch(app,{method:'POST',url:'/api/jobs',headers:t.headers,body:input});const id=response.json().jobId;assert.equal((await waitJob(app,id,t.headers)).status,'failed');assert.equal(Object.keys(JSON.parse(storage.db.prepare('SELECT payload FROM job_checkpoints WHERE job_id=?').get(id).payload)).length,3);storage.close();storage=openDatabase(file);fail=false;app=await createApp({database:storage,provider:providerFor(parts,calls,()=>false)});const resumed=await dispatch(app,{method:'POST',url:`/api/jobs/${id}/resume`,headers:t.headers,body:{}});assert.equal(resumed.status,202);const duplicate=await dispatch(app,{method:'POST',url:`/api/jobs/${id}/resume`,headers:t.headers,body:{}});assert.equal(duplicate.status,409);const result=await waitJob(app,id,t.headers);assert.equal(result.status,'completed',result.error);assert.equal(calls.filter(s=>s==='unpack').length,1);assert.equal(calls.filter(s=>s==='context').length,1);assert.equal(calls.filter(s=>s==='outcomes').length,1);assert.equal(storage.db.prepare('SELECT count(*) n FROM plans').get().n,1);assert.equal(storage.db.prepare('SELECT count(*) n FROM job_checkpoints').get().n,0);assert.equal((await dispatch(app,{method:'POST',url:`/api/jobs/${id}/resume`,headers:t.headers,body:{}})).status,200);assert.equal(storage.db.prepare('SELECT count(*) n FROM plans').get().n,1);
process.env.ILAW_REGISTRATION_ENABLED='true';const other=await teacher(app,'other-retention@example.test');delete process.env.ILAW_REGISTRATION_ENABLED;assert.equal((await dispatch(app,{method:'POST',url:`/api/jobs/${id}/resume`,headers:other.headers,body:{}})).status,404);
}finally{storage.close();delete process.env.ILAW_REGISTRATION_ENABLED;await fs.rm(dir,{recursive:true,force:true});}});
test('retained output is revalidated before reuse',async()=>{const calls=[],parts=await fixture();const p=providerFor(parts,calls,()=>false);await assert.rejects(()=>generateAI(input,{provider:p,checkpoint:{parts:{unpack:{output:{}}}}}));assert.equal(calls.length,0);});
test('source/model mismatch and expired checkpoints fail without provider calls',async()=>{const parts=await fixture(),calls=[];const storage=openDatabase(':memory:');const app=await createApp({database:storage,provider:providerFor(parts,calls,s=>s==='assessment')});try{const t=await teacher(app);const r=await dispatch(app,{method:'POST',url:'/api/jobs',headers:t.headers,body:input});const id=r.json().jobId;await waitJob(app,id,t.headers);const before=calls.length;storage.db.prepare("UPDATE job_checkpoints SET fingerprint='wrong' WHERE job_id=?").run(id);await dispatch(app,{method:'POST',url:`/api/jobs/${id}/resume`,headers:t.headers,body:{}});const result=await waitJob(app,id,t.headers);assert.equal(result.status,'failed');assert.match(result.error,/source\/model changed/);assert.equal(calls.length,before);}finally{storage.close();}});
