import {inflateSync,deflateSync} from 'node:zlib';import {createHash} from 'node:crypto';import {ValidationError} from './schema.js';
const signature=Buffer.from([137,80,78,71,13,10,26,10]);const table=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});const crc=buf=>{let c=0xffffffff;for(const b of buf)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;};
const chunk=(type,data)=>{const name=Buffer.from(type),size=Buffer.alloc(4),check=Buffer.alloc(4);size.writeUInt32BE(data.length);check.writeUInt32BE(crc(Buffer.concat([name,data])));return Buffer.concat([size,name,data,check]);};
export function encodePNG(width,height,rgb){const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=2;const rows=Buffer.alloc(height*(width*3+1));for(let y=0;y<height;y++)rgb.copy(rows,y*(width*3+1)+1,y*width*3,(y+1)*width*3);return Buffer.concat([signature,chunk('IHDR',header),chunk('IDAT',deflateSync(rows)),chunk('IEND',Buffer.alloc(0))]);}
// Canonicalize decoded pixels: discard metadata and executable/vector content.
export function normalizePNG(bytes){
 if(!Buffer.isBuffer(bytes)||bytes.length<45||bytes.length>2_000_000||!bytes.subarray(0,8).equals(signature))throw new ValidationError('Upload a valid PNG of at most 2 MB. JPEG can be converted in the image picker.');
 let at=8,header,palette,alpha,ended=false;const data=[];
 while(at<bytes.length){if(at+12>bytes.length)throw new ValidationError('Truncated PNG');const size=bytes.readUInt32BE(at),type=bytes.subarray(at+4,at+8).toString();if(at+12+size>bytes.length)throw new ValidationError('Invalid PNG chunk');const value=bytes.subarray(at+8,at+8+size);if(crc(bytes.subarray(at+4,at+8+size))!==bytes.readUInt32BE(at+8+size))throw new ValidationError('PNG integrity check failed');if(!header&&type!=='IHDR')throw new ValidationError('PNG header is missing');if(type==='IHDR'){if(header||size!==13)throw new ValidationError('Invalid PNG header');header=value;}else if(type==='IDAT')data.push(value);else if(type==='PLTE')palette=value;else if(type==='tRNS')alpha=value;else if(type==='IEND'){if(size)throw new ValidationError('Invalid PNG end');ended=true;at+=12;break;}at+=size+12;}
 if(!ended||at!==bytes.length||!data.length)throw new ValidationError('Incomplete or trailing PNG data');const width=header.readUInt32BE(),height=header.readUInt32BE(4),color=header[9],channels={0:1,2:3,3:1,4:2,6:4}[color];if(!width||!height||width>3000||height>3000||width*height>4_000_000||header[8]!==8||!channels||header[10]||header[11]||header[12])throw new ValidationError('Use a non-interlaced 8-bit PNG, up to 3000 pixels per side and 4 megapixels');
 if(color===3&&(!palette||palette.length%3||palette.length>768))throw new ValidationError('Invalid PNG palette');if(alpha&&![3,4,6].includes(color))throw new ValidationError('Convert transparency to an RGBA PNG before uploading');const stride=width*channels;let raw;try{raw=inflateSync(Buffer.concat(data),{maxOutputLength:height*(stride+1)});}catch{throw new ValidationError('PNG pixels could not be decoded within the size limit');}if(raw.length!==height*(stride+1))throw new ValidationError('Invalid PNG pixel count');const decoded=Buffer.alloc(height*stride),rgb=Buffer.alloc(width*height*3);
 const paeth=(a,b,c)=>{const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};
 for(let y=0;y<height;y++){const filter=raw[y*(stride+1)];if(filter>4)throw new ValidationError('Invalid PNG filter');for(let x=0;x<stride;x++){const left=x>=channels?decoded[y*stride+x-channels]:0,up=y?decoded[(y-1)*stride+x]:0,corner=y&&x>=channels?decoded[(y-1)*stride+x-channels]:0;const extra=[0,left,up,Math.floor((left+up)/2),paeth(left,up,corner)][filter];decoded[y*stride+x]=(raw[y*(stride+1)+x+1]+extra)&255;}}
 for(let pixel=0;pixel<width*height;pixel++){const p=pixel*channels;let values,a=255;if(color===3){const index=decoded[p];if(index*3+2>=palette.length)throw new ValidationError('PNG palette index is invalid');values=[...palette.subarray(index*3,index*3+3)];a=alpha?.[index]??255;}else if(color===0||color===4){values=[decoded[p],decoded[p],decoded[p]];if(color===4)a=decoded[p+1];}else{values=[decoded[p],decoded[p+1],decoded[p+2]];if(color===6)a=decoded[p+3];}for(let c=0;c<3;c++)rgb[pixel*3+c]=Math.round((values[c]*a+255*(255-a))/255);}
 const png=encodePNG(width,height,rgb);if(png.length>2_000_000)throw new ValidationError('Decoded image exceeds the 2 MB storage limit. Reduce its dimensions before uploading.');return {bytes:png,rgb,width,height,mime:'image/png',hash:createHash('sha256').update(png).digest('hex')};
}
