import fs from 'node:fs';
import {ValidationError} from './schema.js';
const required=(value,name,max=2000)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new ValidationError(`Observation tool ${name} is required (at most ${max} characters)`);};
export function loadObservationTools(file=process.env.ILAW_OBSERVATION_TOOLS_FILE){
 if(!file)return [];
 const tools=JSON.parse(fs.readFileSync(file,'utf8'));if(!Array.isArray(tools)||tools.length>100)throw new ValidationError('Observation tools must be a bounded array');const ids=new Set();
 for(const tool of tools){for(const name of ['id','purpose','issuer','version','schoolYear','careerStage','reviewer','reviewedAt','effectiveFrom','effectiveTo','signedSourceURL','sourceExcerpt'])required(tool[name],name, name==='sourceExcerpt'?20000:2000);if(ids.has(tool.id))throw new ValidationError('Duplicate observation tool');ids.add(tool.id);if(tool.status!=='operator-reviewed'||!['formal-pmes','promotion-reclassification','developmental'].includes(tool.purpose))throw new ValidationError('Only an operator-reviewed tool with an explicit purpose can be loaded');const url=new URL(tool.signedSourceURL);if(url.protocol!=='https:'||!(url.hostname==='deped.gov.ph'||url.hostname.endsWith('.deped.gov.ph')))throw new ValidationError('Use an official signed DepEd source URL');for(const k of ['reviewedAt','effectiveFrom','effectiveTo'])if(!/^\d{4}-\d{2}-\d{2}$/.test(tool[k])||Number.isNaN(Date.parse(tool[k])))throw new ValidationError('Tool dates must use YYYY-MM-DD');if(tool.effectiveFrom>tool.effectiveTo)throw new ValidationError('Observation tool date range is invalid');if(!Array.isArray(tool.indicators)||!tool.indicators.length||tool.indicators.length>100)throw new ValidationError('Reviewed indicators are required');const indicatorIds=new Set();for(const i of tool.indicators){required(i.id,'indicator id',100);required(i.wording,'indicator wording',3000);if(indicatorIds.has(i.id)||!tool.sourceExcerpt.includes(i.wording))throw new ValidationError('Indicators must be unique and occur verbatim in the reviewed excerpt');indicatorIds.add(i.id);}}
 return tools;
}
export function applicableTools(tools,scope){const date=scope.lessonDate||new Date().toISOString().slice(0,10);return tools.filter(t=>t.schoolYear===scope.schoolYear&&t.careerStage===scope.careerStage&&t.purpose===scope.toolPurpose&&t.effectiveFrom<=date&&date<=t.effectiveTo&&(!t.divisionScope||t.divisionScope.includes(scope.division)));}
export function preparationMappings(snapshot,body,tools){
 if(body.confirm!==true||!Array.isArray(body.mappings)||body.mappings.length>12)throw new ValidationError('Confirm at most 12 planned preparation mappings');
 const scope={...snapshot.input,careerStage:body.careerStage,toolPurpose:body.toolPurpose};const available=applicableTools(tools,scope);const activities=new Set(snapshot.sessions.flatMap(s=>s.experiences.map(a=>a.id)));
 return body.mappings.map(m=>{const tool=available.find(t=>t.id===m.toolId),indicator=tool?.indicators.find(i=>i.id===m.indicatorId);if(!indicator||!activities.has(m.activityId))throw new ValidationError('Choose an applicable reviewed tool, indicator and snapshot activity');for(const k of ['teacherAction','anticipatedEvidence','rationale'])required(m[k],k);return {activityId:m.activityId,toolId:tool.id,toolVersion:tool.version,indicatorId:indicator.id,indicatorWording:indicator.wording,signedSourceURL:tool.signedSourceURL,schoolYear:tool.schoolYear,careerStage:tool.careerStage,purpose:tool.purpose,teacherAction:m.teacherAction,anticipatedEvidence:m.anticipatedEvidence,rationale:m.rationale,status:'planned',confirmedAt:new Date().toISOString()};});
}
