import fs from 'node:fs';import {createHash,randomUUID} from 'node:crypto';import {ValidationError} from './schema.js';import {validateRecord} from './curriculum.js';import {validateBOW,matchesBOW} from './bow.js';
const fileURL=new URL('../data-sources/bow-extracted.json',import.meta.url);let cache;
export function sourceCatalog(){if(!cache)cache=JSON.parse(fs.readFileSync(fileURL,'utf8'));return cache;}
export function sourceCoverage(records,{grade,subject,curriculum,schoolYear,term}={}){
 const selected=records.filter(r=>(grade==null||r.grade===Number(grade))&&(!subject||r.subject===subject)&&(!curriculum||r.curriculum===curriculum)&&(!schoolYear||r.schoolYear===schoolYear)&&(!term||r.term===term));const files=sourceCatalog().files.filter(f=>grade==null||f.grades.includes(Number(grade)));
 return {coverageComplete:false,status:selected.some(r=>r.source.status==='verified')?'reviewed-partial':selected.some(r=>r.source.status==='teacher-confirmed')?'teacher-confirmed-partial':files.length?'extracted-pending-review':'unavailable',operatorReviewedRows:selected.filter(r=>r.source.status==='verified').length,teacherConfirmedRows:selected.filter(r=>r.source.status==='teacher-confirmed').length,linkedFiles:files.length,extractedFiles:files.filter(f=>f.status==='extracted-pending-review').length,notice:'Counts do not prove complete coverage, correct school-year applicability or reviewed source-table mapping.'};
}
export function searchCurriculum(db,records,scope,query=''){
 const scoped=records.filter(r=>r.grade===Number(scope.grade)&&r.subject===scope.subject&&(r.source.status==='practice'||r.curriculum===scope.curriculum)&&(!r.schoolYear||r.schoolYear.replace(/[–—]/g,'-')===String(scope.schoolYear||'').replace(/[–—]/g,'-'))&&(!r.term||r.term===scope.term)&&(r.kind!=='budget-of-work'||scope.week==null||matchesBOW(r,scope)));
 if(!query.trim())return scoped.slice(0,100);
 db.exec('CREATE VIRTUAL TABLE IF NOT EXISTS temp.curriculum_search USING fts5(id UNINDEXED,code,title,competency)');db.exec('DELETE FROM temp.curriculum_search');const insert=db.prepare('INSERT INTO temp.curriculum_search VALUES (?,?,?,?)');for(const r of scoped)insert.run(r.id,r.code||'',r.title||'',r.competency);
 const tokens=query.match(/[\p{L}\p{N}]+/gu)?.slice(0,12)||[];if(!tokens.length)return [];
 const exact=scoped.filter(r=>r.code&&r.code.toLowerCase()===query.trim().toLowerCase());const match=tokens.map(t=>`"${t}"*`).join(' OR ');const ranked=db.prepare('SELECT id FROM temp.curriculum_search WHERE curriculum_search MATCH ? ORDER BY bm25(curriculum_search,0,10,3,1) LIMIT 100').all(match).map(x=>scoped.find(r=>r.id===x.id));return [...exact,...ranked.filter(r=>!exact.some(e=>e.id===r.id))];
}
export function candidateRecord(file,body,reviewer){
 if(body.confirm!==true)throw new ValidationError('Confirm the exact excerpt, curriculum, year, term and source-week mapping before import');
 const section=String(body.section||'').trim();const excerpt=String(body.excerpt||'').replace(/\r\n/g,'\n');if(!section||section.length>500||!excerpt||excerpt.length>12000||!file.text.replace(/\r\n/g,'\n').includes(excerpt))throw new ValidationError('Use an exact source excerpt and its page/table location');
 const record={id:randomUUID(),kind:'budget-of-work',grade:Number(body.grade),subject:body.subject,title:body.title||String(body.competency||'').slice(0,100),competency:body.competency,code:body.code||null,curriculum:body.curriculum,curriculumVersion:body.curriculumVersion,schoolYear:body.schoolYear,term:body.term,week:body.week===''||body.week==null?null:Number(body.week),contentStandard:body.contentStandard||null,performanceStandard:body.performanceStandard||null,source:{status:'teacher-confirmed',title:file.title,url:file.directoryURLs[0],fileURL:file.url,date:null,section,excerpt,reviewer,verifiedAt:null,policyVersion:null,effectiveFrom:null,effectiveTo:null,contentHash:createHash('sha256').update(file.text).digest('hex')}};
 if(body.weekStart!==''&&body.weekStart!=null||body.weekEnd!==''&&body.weekEnd!=null){record.weekStart=Number(body.weekStart);record.weekEnd=Number(body.weekEnd);record.weekMapping='range';}else record.weekMapping=record.week==null?'unspecified':'exact';
 if(!file.grades.includes(record.grade))throw new ValidationError('Choose a grade listed in this source directory');validateBOW(record,validateRecord,false);return record;
}
